[package]
name = "HippoX"
version = "0.1.0"
description = "Hippox is an operating system desktop application that helps you operate your computer better."
authors = ["happyboy"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.97.1"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.8.5", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-log = "2.7.0"
# hippox = "0.4.6"
hippox = { path = "D:\\gitproject\\hippox\\core" }
# ffmpegx
ffmpegx = { path = "D:\\gitproject\\ffmpegx" }
# ytdlp
ytdlp = { path = "D:\\gitproject\\ytdlp" }
dirs = "6.0.0"
tokio = "1.52.3"
uuid = "1.20.0"
chrono = "0.4.44"
once_cell = "1.21.4"
async-trait = "0.1.89"
fs_extra = "1.3.0"
rfd = "0.17.2"
walkdir = "2.5.0"
nix = "0.31.3"
sysinfo = "0.36.1"
memcontext = "0.3.5"
tauri-plugin-shell = "2"
futures = "0.3.32"
tauri-plugin-autostart = "2.5.1"
winapi = "0.3.9"
base64 = "0.22.1"
scraper = "0.27.0"
reqwest = "0.13.3"
url = "2.5.8"
cron = "0.16.0"
tauri-plugin-fs = "2.5.1"
tauri-plugin-dialog = "2.7.1"
regex = "1.12.4"
rayon = "1.10.0"
rand = "0.9.4"
encoding_rs = "0.8.35"
rodio = "0.21.1"
lazy_static = "1.5.0"
image = "0.25.6"
num_cpus = "1.17.0"
fast_image_resize = "5.1.4"
pollster = "1.0.1"
wgpu = "24.0.5"
bytemuck = "1.25.2"
zune-jpeg = "0.5.15"
dashmap = "6.2.1"
simple_logger = "5.2.0"
imageproc = "0.27.0"
parking_lot = "0.12.5"
webbrowser = "1.2.4"
wmi = "0.18.4"
