/**
 * Style factory for the material preview window.
 */
export const getStyles = (
    isDark: boolean,
    imageScale: number,
    isDragging: boolean,
    imageRotation: number,
    imagePosition: { x: number; y: number },
) => ({
    container: {
        backgroundColor: "var(--bg-primary)",
        border: `1px solid var(--border-color)`,
        boxShadow: isDark
            ? "0 4px 12px rgba(0,0,0,0.4)"
            : "0 4px 12px rgba(0,0,0,0.15)",
        overflow: "hidden" as const,
        width: "100%",
        height: "100%",
        display: "flex" as const,
        flexDirection: "column" as const,
    },
    topBar: {
        height: "35px",
        background: "var(--bg-secondary)",
        borderBottom: `1px solid var(--border-color)`,
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "space-between" as const,
        padding: "0 12px",
        flexShrink: 0 as const,
    },
    topBarLeft: {
        display: "flex" as const,
        alignItems: "center" as const,
        gap: "6px",
        flexShrink: 0 as const,
    },
    topBarCenter: {
        flex: 1,
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        overflow: "hidden" as const,
        padding: "0 8px",
    },
    topBarTitle: {
        fontSize: "13px",
        fontWeight: 500,
        color: "var(--text-primary)",
        overflow: "hidden" as const,
        textOverflow: "ellipsis" as const,
        whiteSpace: "nowrap" as const,
        maxWidth: "300px",
    },
    topBarRight: {
        display: "flex" as const,
        alignItems: "center" as const,
        gap: "2px",
        flexShrink: 0 as const,
    },
    windowBtn: {
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        width: "32px",
        height: "32px",
        background: "transparent" as const,
        border: "none" as const,
        cursor: "pointer" as const,
        color: "var(--text-secondary)",
        fontSize: "15px",
        borderRadius: "0",
        flexShrink: 0 as const,
    },
    content: {
        flex: 1,
        display: "flex" as const,
        flexDirection: "column" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        padding: "8px",
        overflow: "hidden" as const,
        minHeight: 0,
        position: "relative" as const,
    },
    previewContainer: {
        width: "100%",
        height: "100%",
        display: "flex" as const,
        flexDirection: "column" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        overflow: "hidden" as const,
    },
    video: {
        width: "100%",
        height: "100%",
        maxHeight: "100%",
        borderRadius: "4px",
        backgroundColor: "#000",
        objectFit: "contain" as const,
    },
    imageContainer: {
        width: "100%",
        height: "100%",
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        overflow: "hidden" as const,
        cursor: imageScale > 1 ? "grab" : "default",
        position: "relative" as const,
        backgroundColor: "var(--bg-tertiary)",
    },
    imageWrapper: {
        transform: `scale(${imageScale}) rotate(${imageRotation}deg) translate(${imagePosition.x / imageScale}px, ${imagePosition.y / imageScale}px)`,
        transition: isDragging ? "none" : "transform 0.1s ease",
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        width: "100%",
        height: "100%",
    },
    image: {
        maxWidth: "100%",
        maxHeight: "100%",
        objectFit: "contain" as const,
        borderRadius: "4px",
        userSelect: "none" as const,
        WebkitUserSelect: "none" as const,
    },
    imageControls: {
        position: "absolute" as const,
        bottom: "16px",
        left: "50%",
        transform: "translateX(-50%)",
        display: "flex" as const,
        alignItems: "center" as const,
        gap: "6px",
        padding: "6px 12px",
        backgroundColor: "var(--bg-secondary)",
        borderRadius: "8px",
        border: `1px solid var(--border-color)`,
        backdropFilter: "blur(8px)",
        zIndex: 10,
    },
    imageControlBtn: {
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        width: "28px",
        height: "28px",
        background: "transparent" as const,
        border: "none" as const,
        borderRadius: "4px",
        cursor: "pointer" as const,
        color: "var(--text-primary)",
        transition: "background 0.15s",
    },
    imageControlText: {
        fontSize: "11px",
        color: "var(--text-muted)",
        padding: "0 6px",
        minWidth: "40px",
        textAlign: "center" as const,
        fontFamily: "monospace",
    },
    textPreview: {
        width: "100%",
        height: "100%",
        flex: 1,
        borderRadius: "4px",
        overflow: "hidden" as const,
        backgroundColor: isDark ? "#1e1e1e" : "#ffffff",
        position: "relative" as const,
    },
    editorContainer: {
        width: "100%",
        height: "100%",
        position: "relative" as const,
    },
    waveformContainer: {
        width: "100%",
        display: "flex" as const,
        flexDirection: "column" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        padding: "16px",
        backgroundColor: "var(--bg-secondary)",
        borderRadius: "4px",
        minHeight: "140px",
        flex: 1,
        overflow: "hidden" as const,
        position: "relative" as const,
    },
    audioPlaceholder: {
        fontSize: "48px",
        color: "var(--text-muted)",
    },
    controls: {
        display: "flex" as const,
        alignItems: "center" as const,
        gap: "12px",
        padding: "8px 16px",
        borderTop: `1px solid var(--border-color)`,
        backgroundColor: "var(--bg-secondary)",
        flexShrink: 0 as const,
    },
    playBtn: {
        background: "none" as const,
        border: "none" as const,
        cursor: "pointer" as const,
        fontSize: "20px",
        color: "var(--text-primary)",
        padding: "4px 8px",
        borderRadius: "4px",
        transition: "background 0.15s",
    },
    timeDisplay: {
        fontSize: "12px",
        color: "var(--text-muted)",
        fontFamily: "monospace",
        minWidth: "80px",
    },
    progressBar: {
        flex: 1,
        height: "4px",
        backgroundColor: "var(--bg-tertiary)",
        borderRadius: "2px",
        cursor: "pointer" as const,
        position: "relative" as const,
        overflow: "hidden" as const,
    },
    progressFill: {
        height: "100%",
        backgroundColor: "var(--accent-green)",
        borderRadius: "2px",
        transition: "width 0.1s",
    },
    info: {
        display: "grid" as const,
        gridTemplateColumns: "1fr 1fr",
        gap: "4px 16px",
        padding: "6px 16px",
        fontSize: "11px",
        color: "var(--text-muted)",
        width: "100%",
        borderTop: `1px solid var(--border-color)`,
        flexShrink: 0 as const,
    },
    infoLabel: {
        color: "var(--text-muted)",
    },
    infoValue: {
        color: "var(--text-primary)",
        textAlign: "right" as const,
    },
    emptyState: {
        display: "flex" as const,
        flexDirection: "column" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        gap: "12px",
        color: "var(--text-muted)",
        fontSize: "14px",
    },
});