export const getStyles = (
    isDark: boolean,
    imageScale: number,
    isDragging: boolean,
    imageRotation: number,
    imagePosition: { x: number; y: number },
) => ({
    container: {
        backgroundColor: isDark ? "#1a1d26" : "#ffffff",
        border: `1px solid ${isDark ? "#2d303a" : "#e5e7eb"}`,
        boxShadow: isDark
            ? "0 4px 12px rgba(0,0,0,0.4)"
            : "0 4px 12px rgba(0,0,0,0.15)",
        overflow: "hidden" as const,
        width: "100%",
        height: "100%",
        display: "flex" as const,
        flexDirection: "column" as const,
    },
    topBar: {
        height: "35px",
        background: isDark ? "#22252f" : "#f9fafb",
        borderBottom: `1px solid ${isDark ? "#2d303a" : "#e5e7eb"}`,
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "space-between" as const,
        padding: "0 12px",
        flexShrink: 0 as const,
        WebkitAppRegion: "drag" as const,
        appRegion: "drag" as const,
    },
    topBarLeft: {
        display: "flex" as const,
        alignItems: "center" as const,
        gap: "6px",
        flexShrink: 0 as const,
        WebkitAppRegion: "drag" as const,
        appRegion: "drag" as const,
    },
    topBarCenter: {
        flex: 1,
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        WebkitAppRegion: "drag" as const,
        appRegion: "drag" as const,
        overflow: "hidden" as const,
        padding: "0 8px",
    },
    topBarTitle: {
        fontSize: "13px",
        fontWeight: 500,
        color: isDark ? "#e8edf2" : "#111827",
        overflow: "hidden" as const,
        textOverflow: "ellipsis" as const,
        whiteSpace: "nowrap" as const,
        WebkitAppRegion: "drag" as const,
        appRegion: "drag" as const,
        maxWidth: "300px",
    },
    topBarRight: {
        display: "flex" as const,
        alignItems: "center" as const,
        gap: "2px",
        WebkitAppRegion: "no-drag" as const,
        appRegion: "no-drag" as const,
        flexShrink: 0 as const,
    },
    windowBtn: {
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        width: "32px",
        height: "32px",
        background: "transparent" as const,
        border: "none" as const,
        cursor: "pointer" as const,
        color: isDark ? "#9ca3af" : "#6b7280",
        fontSize: "15px",
        borderRadius: "0",
        flexShrink: 0 as const,
        WebkitAppRegion: "no-drag" as const,
        appRegion: "no-drag" as const,
    },
    content: {
        flex: 1,
        display: "flex" as const,
        flexDirection: "column" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        padding: "8px",
        overflow: "hidden" as const,
        minHeight: 0,
        position: "relative" as const,
    },
    previewContainer: {
        width: "100%",
        height: "100%",
        display: "flex" as const,
        flexDirection: "column" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        overflow: "hidden" as const,
    },
    video: {
        width: "100%",
        height: "100%",
        maxHeight: "100%",
        borderRadius: "4px",
        backgroundColor: "#000",
        objectFit: "contain" as const,
    },
    imageContainer: {
        width: "100%",
        height: "100%",
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        overflow: "hidden" as const,
        cursor: imageScale > 1 ? "grab" : "default",
        position: "relative" as const,
        backgroundColor: isDark ? "#0d0d0d" : "#f0f0f0",
    },
    imageWrapper: {
        transform: `scale(${imageScale}) rotate(${imageRotation}deg) translate(${imagePosition.x / imageScale}px, ${imagePosition.y / imageScale}px)`,
        transition: isDragging ? "none" : "transform 0.1s ease",
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        width: "100%",
        height: "100%",
    },
    image: {
        maxWidth: "100%",
        maxHeight: "100%",
        objectFit: "contain" as const,
        borderRadius: "4px",
        userSelect: "none" as const,
        WebkitUserSelect: "none" as const,
    },
    imageControls: {
        position: "absolute" as const,
        bottom: "16px",
        left: "50%",
        transform: "translateX(-50%)",
        display: "flex" as const,
        alignItems: "center" as const,
        gap: "6px",
        padding: "6px 12px",
        backgroundColor: isDark ? "rgba(0,0,0,0.75)" : "rgba(255,255,255,0.85)",
        borderRadius: "8px",
        border: `1px solid ${isDark ? "rgba(255,255,255,0.1)" : "rgba(0,0,0,0.1)"}`,
        backdropFilter: "blur(8px)",
        zIndex: 10,
    },
    imageControlBtn: {
        display: "flex" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        width: "28px",
        height: "28px",
        background: "transparent" as const,
        border: "none" as const,
        borderRadius: "4px",
        cursor: "pointer" as const,
        color: isDark ? "#e8edf2" : "#111827",
        transition: "background 0.15s",
    },
    imageControlText: {
        fontSize: "11px",
        color: isDark ? "#9ca3af" : "#6b7280",
        padding: "0 6px",
        minWidth: "40px",
        textAlign: "center" as const,
        fontFamily: "monospace",
    },
    textPreview: {
        width: "100%",
        height: "100%",
        flex: 1,
        borderRadius: "4px",
        overflow: "hidden" as const,
        backgroundColor: isDark ? "#1e1e1e" : "#ffffff",
        position: "relative" as const,
    },
    editorContainer: {
        width: "100%",
        height: "100%",
        position: "relative" as const,
    },
    waveformContainer: {
        width: "100%",
        display: "flex" as const,
        flexDirection: "column" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        padding: "16px",
        backgroundColor: isDark ? "#22252f" : "#f3f4f6",
        borderRadius: "4px",
        minHeight: "140px",
        flex: 1,
        overflow: "hidden" as const,
        position: "relative" as const,
    },
    audioPlaceholder: {
        fontSize: "48px",
        color: isDark ? "#4a4f5a" : "#d1d5db",
    },
    controls: {
        display: "flex" as const,
        alignItems: "center" as const,
        gap: "12px",
        padding: "8px 16px",
        borderTop: `1px solid ${isDark ? "#2d303a" : "#e5e7eb"}`,
        backgroundColor: isDark ? "#22252f" : "#f9fafb",
        flexShrink: 0 as const,
    },
    playBtn: {
        background: "none" as const,
        border: "none" as const,
        cursor: "pointer" as const,
        fontSize: "20px",
        color: isDark ? "#e8edf2" : "#111827",
        padding: "4px 8px",
        borderRadius: "4px",
        transition: "background 0.15s",
    },
    timeDisplay: {
        fontSize: "12px",
        color: isDark ? "#9ca3af" : "#6b7280",
        fontFamily: "monospace",
        minWidth: "80px",
    },
    progressBar: {
        flex: 1,
        height: "4px",
        backgroundColor: isDark ? "#3a3f4a" : "#e5e7eb",
        borderRadius: "2px",
        cursor: "pointer" as const,
        position: "relative" as const,
        overflow: "hidden" as const,
    },
    progressFill: {
        height: "100%",
        backgroundColor: "#4ec9b0",
        borderRadius: "2px",
        transition: "width 0.1s",
    },
    info: {
        display: "grid" as const,
        gridTemplateColumns: "1fr 1fr",
        gap: "4px 16px",
        padding: "6px 16px",
        fontSize: "11px",
        color: isDark ? "#9ca3af" : "#6b7280",
        width: "100%",
        borderTop: `1px solid ${isDark ? "#2d303a" : "#e5e7eb"}`,
        flexShrink: 0 as const,
    },
    infoLabel: {
        color: isDark ? "#6b7280" : "#9ca3af",
    },
    infoValue: {
        color: isDark ? "#e8edf2" : "#111827",
        textAlign: "right" as const,
    },
    emptyState: {
        display: "flex" as const,
        flexDirection: "column" as const,
        alignItems: "center" as const,
        justifyContent: "center" as const,
        gap: "12px",
        color: isDark ? "#6b7280" : "#9ca3af",
        fontSize: "14px",
    },
});