export const zhDefaultPrompts = [
    "请获取当前系统的CPU信息、内存使用情况、磁盘使用情况和系统运行时间。",
    "请获取当前的系统日期和时间。",
    "请获取当前主机的名称、用户名和IP地址。",
    "请列出当前工作目录下的所有文件和文件夹。",
    "请生成一个1到100之间的随机整数。",
    "请生成一个长度为16位的随机字符串。",
    "请生成一个UUID。",
    "请生成一个包含大小写字母、数字和特殊符号的12位随机密码。",
    "请读取当前目录下的 README.md 文件内容。",
    "请在当前目录下创建一个名为 test.txt 的文件，内容为 'Hello Hippox'。",
    "请将当前目录下的 test.txt 复制为 test_backup.txt。",
    "请将当前目录下的所有 .txt 文件压缩成 archive.zip。",
    "请解压当前目录下的 archive.zip 文件到 extract 文件夹。",
    "请计算当前目录下 README.md 文件的 MD5 和 SHA256 哈希值。",
    "请将字符串 'Hello Hippox' 进行 Base64 编码。",
    "请将 'SGVsbG8gSGlwcG94' 进行 Base64 解码。",
    "请测试 8.8.8.8 的网络连通性。",
    "请测试 8.8.8.8 的 80 端口是否开放。",
    "请查询 google.com 的IP地址。",
    "请查询 8.8.8.8 的IP地址信息。",
    "请验证 192.168.1.1 是否为有效的IP地址。",
    "请获取当前系统剪贴板中的内容。",
    "请将字符串 'Hippox AI Runtime' 写入系统剪贴板。",
    "请对比 'Hello World' 和 'Hello Hippox' 的差异。",
    "请将以下文本按字母顺序排序：['banana', 'apple', 'cherry', 'date']。",
    "请去除以下重复项：['a', 'b', 'a', 'c', 'b', 'd']。",
    "请检查字符串 'user@example.com' 是否符合邮箱格式。",
    "请从文本 '我的电话是13812345678' 中提取手机号码。",
    "请列出当前系统正在运行的所有进程。",
    "请获取 PID 为 1 的进程详细信息。",
    "请杀死 PID 为 1234 的进程。",
    "请检查进程名为 'chrome' 的进程是否正在运行。",
    "请获取当前系统的负载平均值。",
    "请获取当前系统的电池信息。",
    "请发送一条系统通知，内容为 '任务已完成'。",
    "请将系统剪贴板内容清空。",
    "请将字符串 'https://www.example.com' 进行 URL 编码。",
    "请对 IP 范围 192.168.1.0/24 进行扫描，列出所有活跃主机。",
    "请查询 localhost 的反向 DNS 解析。",
    "请批量查询以下域名的IP地址：google.com, github.com, stackoverflow.com。",
    "请将字符串 'Hello World' 转换为小写。",
    "请将字符串 'hello world' 转换为大写。",
    "请统计字符串 'hello hello world' 中每个单词出现的次数。",
    "请反转字符串 'Hippox'。",
    "请检查当前工作目录是否存在。",
    "请删除当前目录下的 temp.txt 文件。",
    "请创建一个名为 new_folder 的新目录。",
    "请删除名为 empty_folder 的空目录。",
    "请将当前目录下所有 .log 文件移动到 logs 目录。",
    "请列出当前目录下所有大于 10MB 的文件。",
    "请计算当前目录下所有文件的总大小。",
    "请获取当前用户的 home 目录路径。",
    "请获取当前系统的临时目录路径。",
    "请获取当前工作目录的绝对路径。",
    "请获取当前系统的环境变量 PATH 的值。",
    "请重启当前操作系统。",
    "请关闭当前操作系统。",
    "请让系统进入休眠状态。",
    "请锁定当前系统屏幕。",
    "请注销当前用户。",
    "请让系统进入睡眠状态。",
    "请获取系统的运行时间。",
    "请获取系统的负载平均值。",
    "请获取系统的电池电量信息。",
    "请获取系统的网络接口信息。",
    "请扫描本地网络中的所有活跃主机。",
    "请查询当前本机的内网IP地址。",
    "请测试与 github.com 的网络连通性。",
    "请测试与 1.1.1.1 的 TCP 443 端口连通性。",
    "请批量 ping 以下地址：8.8.8.8, 1.1.1.1, 114.114.114.114。",
    "请查询 baidu.com 的 DNS 解析结果。",
    "请查询 8.8.8.8 的 PTR 反向解析记录。",
    "请批量查询以下域名的 DNS：google.com, github.com, stackoverflow.com。",
    "请验证 IP 地址 10.0.0.1 是否有效。",
    "请获取 IP 地址 8.8.8.8 的地理位置信息。",
    "请列出当前系统所有环境变量。",
    "请获取当前系统的临时文件夹路径。",
    "请获取当前系统的用户名。",
    "请获取当前系统的主机名。",
    "请获取当前系统的操作系统版本信息。",
    "请获取当前系统的 CPU 型号和核心数。",
    "请获取当前系统的总内存大小和可用内存。",
    "请获取当前系统所有磁盘分区的使用情况。",
    "请获取当前系统所有正在监听的端口。",
    "请检查 PID 为 1 的进程是否在运行。",
    "请列出所有包含 'python' 关键词的进程。",
    "请生成一个 8 位随机数字验证码。",
    "请生成一个 24 位随机字母数字混合字符串。",
    "请计算字符串 'Hippox Runtime' 的 MD5 哈希值。",
    "请计算字符串 'Hello World' 的 SHA256 哈希值。",
    "请对字符串 'SGVsbG8gSGlwcG94' 进行 Base64 解码。",
    "请对字符串 'Hippox AI' 进行 Base64 编码。",
    "请获取当前的 ISO 格式时间戳。",
    "请获取当前的时间戳（毫秒）。",
    "请判断当前目录是否存在。",
    "请列出当前目录下所有隐藏文件。",
    "请统计当前目录下的文件数量。",
    "请清空系统剪贴板。",
    "请将 'Hippox AI Runtime' 写入剪贴板。",
    "请对比字符串 'abc123' 和 'abc456' 的差异。",
    "请将以下列表去重：[1, 2, 2, 3, 4, 4, 5]。",
    "请从文本 '订单号：ORD-12345678' 中提取订单号。",
    "请验证邮箱 'test@example.com' 格式是否正确。",
];

export const enDefaultPrompts = [
    "Get the current system's CPU information, memory usage, disk usage, and system uptime.",
    "Get the current system date and time.",
    "Get the current hostname, username, and IP address.",
    "List all files and folders in the current working directory.",
    "Generate a random integer between 1 and 100.",
    "Generate a 16-character random string.",
    "Generate a UUID.",
    "Generate a 12-character random password containing uppercase, lowercase, numbers, and special symbols.",
    "Read the content of README.md in the current directory.",
    "Create a file named test.txt in the current directory with content 'Hello Hippox'.",
    "Copy test.txt to test_backup.txt in the current directory.",
    "Compress all .txt files in the current directory into archive.zip.",
    "Extract archive.zip to the extract folder.",
    "Calculate the MD5 and SHA256 hash of README.md in the current directory.",
    "Base64 encode the string 'Hello Hippox'.",
    "Base64 decode the string 'SGVsbG8gSGlwcG94'.",
    "Test network connectivity to 8.8.8.8.",
    "Test if port 80 on 8.8.8.8 is open.",
    "Look up the IP address of google.com.",
    "Look up IP information for 8.8.8.8.",
    "Validate whether 192.168.1.1 is a valid IP address.",
    "Get the current system clipboard content.",
    "Write the string 'Hippox AI Runtime' to the system clipboard.",
    "Compare the difference between 'Hello World' and 'Hello Hippox'.",
    "Sort the following text alphabetically: ['banana', 'apple', 'cherry', 'date'].",
    "Remove duplicates from: ['a', 'b', 'a', 'c', 'b', 'd'].",
    "Check if the string 'user@example.com' matches email format.",
    "Extract the phone number from the text 'My phone is 13812345678'.",
    "List all running processes on the current system.",
    "Get detailed information for process with PID 1.",
    "Kill the process with PID 1234.",
    "Check if a process named 'chrome' is running.",
    "Get the current system load average.",
    "Get the current system battery information.",
    "Send a system notification with content 'Task completed'.",
    "Clear the system clipboard content.",
    "URL encode the string 'https://www.example.com'.",
    "Scan the IP range 192.168.1.0/24 and list all active hosts.",
    "Perform a reverse DNS lookup for localhost.",
    "Batch lookup IP addresses for the following domains: google.com, github.com, stackoverflow.com.",
    "Convert the string 'Hello World' to lowercase.",
    "Convert the string 'hello world' to uppercase.",
    "Count the frequency of each word in the string 'hello hello world'.",
    "Reverse the string 'Hippox'.",
    "Check if the current working directory exists.",
    "Delete the file temp.txt in the current directory.",
    "Create a new directory named new_folder.",
    "Delete the empty directory named empty_folder.",
    "Move all .log files in the current directory to the logs directory.",
    "List all files larger than 10MB in the current directory.",
    "Calculate the total size of all files in the current directory.",
    "Get the home directory path of the current user.",
    "Get the temporary directory path of the current system.",
    "Get the absolute path of the current working directory.",
    "Get the value of the PATH environment variable.",
    "Restart the current operating system.",
    "Shut down the current operating system.",
    "Hibernate the current system.",
    "Lock the current system screen.",
    "Log out the current user.",
    "Put the system to sleep.",
    "Get the system uptime.",
    "Get the system load average.",
    "Get the system battery information.",
    "Get the system network interface information.",
    "Scan all active hosts on the local network.",
    "Get the local internal IP address of this machine.",
    "Test network connectivity to github.com.",
    "Test TCP port 443 connectivity to 1.1.1.1.",
    "Batch ping the following addresses: 8.8.8.8, 1.1.1.1, 114.114.114.114.",
    "Look up the DNS resolution of baidu.com.",
    "Look up the PTR reverse DNS record for 8.8.8.8.",
    "Batch DNS lookup for the following domains: google.com, github.com, stackoverflow.com.",
    "Validate whether IP address 10.0.0.1 is valid.",
    "Get geolocation information for IP address 8.8.8.8.",
    "List all environment variables on the current system.",
    "Get the temporary directory path of the current system.",
    "Get the username of the current system.",
    "Get the hostname of the current system.",
    "Get the operating system version information.",
    "Get the CPU model and core count of the current system.",
    "Get the total memory and available memory of the current system.",
    "Get the disk usage of all partitions on the current system.",
    "List all listening ports on the current system.",
    "Check if process with PID 1 is running.",
    "List all processes containing the keyword 'python'.",
    "Generate an 8-digit random numeric verification code.",
    "Generate a 24-character random alphanumeric string.",
    "Calculate the MD5 hash of the string 'Hippox Runtime'.",
    "Calculate the SHA256 hash of the string 'Hello World'.",
    "Base64 decode the string 'SGVsbG8gSGlwcG94'.",
    "Base64 encode the string 'Hippox AI'.",
    "Get the current ISO format timestamp.",
    "Get the current timestamp in milliseconds.",
    "Check if the current directory exists.",
    "List all hidden files in the current directory.",
    "Count the number of files in the current directory.",
    "Clear the system clipboard.",
    "Write 'Hippox AI Runtime' to the clipboard.",
    "Compare the difference between strings 'abc123' and 'abc456'.",
    "Remove duplicates from the list: [1, 2, 2, 3, 4, 4, 5].",
    "Extract the order number from the text 'Order number: ORD-12345678'.",
    "Validate whether the email 'test@example.com' format is correct.",
];