export const zhDefaultPrompts = [
    "请获取当前系统的CPU信息、内存使用情况、磁盘使用情况和系统运行时间。",
    "请获取当前的系统日期和时间。",
    "请获取当前主机的名称、用户名和IP地址。",
    "请列出当前工作目录下的所有文件和文件夹。",
    "请生成一个1到100之间的随机整数。",
    "请生成一个长度为16位的随机字符串。",
    "请生成一个UUID。",
    "请生成一个包含大小写字母、数字和特殊符号的12位随机密码。",
    "请读取当前目录下的 README.md 文件内容。",
    "请在当前目录下创建一个名为 test.txt 的文件，内容为 'Hello Hippox'。",
    "请将当前目录下的 test.txt 复制为 test_backup.txt。",
    "请将当前目录下的所有 .txt 文件压缩成 archive.zip。",
    "请解压当前目录下的 archive.zip 文件到 extract 文件夹。",
    "请计算当前目录下 README.md 文件的 MD5 和 SHA256 哈希值。",
    "请将字符串 'Hello Hippox' 进行 Base64 编码。",
    "请将 'SGVsbG8gSGlwcG94' 进行 Base64 解码。",
    "请测试 8.8.8.8 的网络连通性。",
    "请测试 8.8.8.8 的 80 端口是否开放。",
    "请查询 google.com 的IP地址。",
    "请查询 8.8.8.8 的IP地址信息。",
    "请验证 192.168.1.1 是否为有效的IP地址。",
    "请获取当前系统剪贴板中的内容。",
    "请将字符串 'Hippox AI Runtime' 写入系统剪贴板。",
    "请对比 'Hello World' 和 'Hello Hippox' 的差异。",
    "请将以下文本按字母顺序排序：['banana', 'apple', 'cherry', 'date']。",
    "请去除以下重复项：['a', 'b', 'a', 'c', 'b', 'd']。",
    "请检查字符串 'user@example.com' 是否符合邮箱格式。",
    "请从文本 '我的电话是13812345678' 中提取手机号码。",
    "请列出当前系统正在运行的所有进程。",
    "请获取 PID 为 1 的进程详细信息。",
    "请杀死 PID 为 1234 的进程。",
    "请检查进程名为 'chrome' 的进程是否正在运行。",
    "请获取当前系统的负载平均值。",
    "请获取当前系统的电池信息。",
    "请发送一条系统通知，内容为 '任务已完成'。",
    "请将系统剪贴板内容清空。",
    "请将字符串 'https://www.example.com' 进行 URL 编码。",
    "请对 IP 范围 192.168.1.0/24 进行扫描，列出所有活跃主机。",
    "请查询 localhost 的反向 DNS 解析。",
    "请批量查询以下域名的IP地址：google.com, github.com, stackoverflow.com。",
    "请将字符串 'Hello World' 转换为小写。",
    "请将字符串 'hello world' 转换为大写。",
    "请统计字符串 'hello hello world' 中每个单词出现的次数。",
    "请反转字符串 'Hippox'。",
    "请检查当前工作目录是否存在。",
    "请删除当前目录下的 temp.txt 文件。",
    "请创建一个名为 new_folder 的新目录。",
    "请删除名为 empty_folder 的空目录。",
    "请将当前目录下所有 .log 文件移动到 logs 目录。",
    "请列出当前目录下所有大于 10MB 的文件。",
    "请计算当前目录下所有文件的总大小。",
    "请获取当前用户的 home 目录路径。",
    "请获取当前系统的临时目录路径。",
    "请获取当前工作目录的绝对路径。",
    "请获取当前系统的环境变量 PATH 的值。",
    "请重启当前操作系统。",
    "请关闭当前操作系统。",
    "请让系统进入休眠状态。",
    "请锁定当前系统屏幕。",
    "请注销当前用户。",
    "请让系统进入睡眠状态。",
    "请获取系统的运行时间。",
    "请获取系统的负载平均值。",
    "请获取系统的电池电量信息。",
    "请获取系统的网络接口信息。",
    "请扫描本地网络中的所有活跃主机。",
    "请查询当前本机的内网IP地址。",
    "请测试与 github.com 的网络连通性。",
    "请测试与 1.1.1.1 的 TCP 443 端口连通性。",
    "请批量 ping 以下地址：8.8.8.8, 1.1.1.1, 114.114.114.114。",
    "请查询 baidu.com 的 DNS 解析结果。",
    "请查询 8.8.8.8 的 PTR 反向解析记录。",
    "请批量查询以下域名的 DNS：google.com, github.com, stackoverflow.com。",
    "请验证 IP 地址 10.0.0.1 是否有效。",
    "请获取 IP 地址 8.8.8.8 的地理位置信息。",
    "请列出当前系统所有环境变量。",
    "请获取当前系统的临时文件夹路径。",
    "请获取当前系统的用户名。",
    "请获取当前系统的主机名。",
    "请获取当前系统的操作系统版本信息。",
    "请获取当前系统的 CPU 型号和核心数。",
    "请获取当前系统的总内存大小和可用内存。",
    "请获取当前系统所有磁盘分区的使用情况。",
    "请获取当前系统所有正在监听的端口。",
    "请检查 PID 为 1 的进程是否在运行。",
    "请列出所有包含 'python' 关键词的进程。",
    "请生成一个 8 位随机数字验证码。",
    "请生成一个 24 位随机字母数字混合字符串。",
    "请计算字符串 'Hippox Runtime' 的 MD5 哈希值。",
    "请计算字符串 'Hello World' 的 SHA256 哈希值。",
    "请对字符串 'SGVsbG8gSGlwcG94' 进行 Base64 解码。",
    "请对字符串 'Hippox AI' 进行 Base64 编码。",
    "请获取当前的 ISO 格式时间戳。",
    "请获取当前的时间戳（毫秒）。",
    "请判断当前目录是否存在。",
    "请列出当前目录下所有隐藏文件。",
    "请统计当前目录下的文件数量。",
    "请清空系统剪贴板。",
    "请将 'Hippox AI Runtime' 写入剪贴板。",
    "请对比字符串 'abc123' 和 'abc456' 的差异。",
    "请将以下列表去重：[1, 2, 2, 3, 4, 4, 5]。",
    "请从文本 '订单号：ORD-12345678' 中提取订单号。",
    "请验证邮箱 'test@example.com' 格式是否正确。",
];

export const enDefaultPrompts = [
    "Get the current system's CPU information, memory usage, disk usage, and system uptime.",
    "Get the current system date and time.",
    "Get the current hostname, username, and IP address.",
    "List all files and folders in the current working directory.",
    "Generate a random integer between 1 and 100.",
    "Generate a 16-character random string.",
    "Generate a UUID.",
    "Generate a 12-character random password containing uppercase, lowercase, numbers, and special symbols.",
    "Read the content of README.md in the current directory.",
    "Create a file named test.txt in the current directory with content 'Hello Hippox'.",
    "Copy test.txt to test_backup.txt in the current directory.",
    "Compress all .txt files in the current directory into archive.zip.",
    "Extract archive.zip to the extract folder.",
    "Calculate the MD5 and SHA256 hash of README.md in the current directory.",
    "Base64 encode the string 'Hello Hippox'.",
    "Base64 decode the string 'SGVsbG8gSGlwcG94'.",
    "Test network connectivity to 8.8.8.8.",
    "Test if port 80 on 8.8.8.8 is open.",
    "Look up the IP address of google.com.",
    "Look up IP information for 8.8.8.8.",
    "Validate whether 192.168.1.1 is a valid IP address.",
    "Get the current system clipboard content.",
    "Write the string 'Hippox AI Runtime' to the system clipboard.",
    "Compare the difference between 'Hello World' and 'Hello Hippox'.",
    "Sort the following text alphabetically: ['banana', 'apple', 'cherry', 'date'].",
    "Remove duplicates from: ['a', 'b', 'a', 'c', 'b', 'd'].",
    "Check if the string 'user@example.com' matches email format.",
    "Extract the phone number from the text 'My phone is 13812345678'.",
    "List all running processes on the current system.",
    "Get detailed information for process with PID 1.",
    "Kill the process with PID 1234.",
    "Check if a process named 'chrome' is running.",
    "Get the current system load average.",
    "Get the current system battery information.",
    "Send a system notification with content 'Task completed'.",
    "Clear the system clipboard content.",
    "URL encode the string 'https://www.example.com'.",
    "Scan the IP range 192.168.1.0/24 and list all active hosts.",
    "Perform a reverse DNS lookup for localhost.",
    "Batch lookup IP addresses for the following domains: google.com, github.com, stackoverflow.com.",
    "Convert the string 'Hello World' to lowercase.",
    "Convert the string 'hello world' to uppercase.",
    "Count the frequency of each word in the string 'hello hello world'.",
    "Reverse the string 'Hippox'.",
    "Check if the current working directory exists.",
    "Delete the file temp.txt in the current directory.",
    "Create a new directory named new_folder.",
    "Delete the empty directory named empty_folder.",
    "Move all .log files in the current directory to the logs directory.",
    "List all files larger than 10MB in the current directory.",
    "Calculate the total size of all files in the current directory.",
    "Get the home directory path of the current user.",
    "Get the temporary directory path of the current system.",
    "Get the absolute path of the current working directory.",
    "Get the value of the PATH environment variable.",
    "Restart the current operating system.",
    "Shut down the current operating system.",
    "Hibernate the current system.",
    "Lock the current system screen.",
    "Log out the current user.",
    "Put the system to sleep.",
    "Get the system uptime.",
    "Get the system load average.",
    "Get the system battery information.",
    "Get the system network interface information.",
    "Scan all active hosts on the local network.",
    "Get the local internal IP address of this machine.",
    "Test network connectivity to github.com.",
    "Test TCP port 443 connectivity to 1.1.1.1.",
    "Batch ping the following addresses: 8.8.8.8, 1.1.1.1, 114.114.114.114.",
    "Look up the DNS resolution of baidu.com.",
    "Look up the PTR reverse DNS record for 8.8.8.8.",
    "Batch DNS lookup for the following domains: google.com, github.com, stackoverflow.com.",
    "Validate whether IP address 10.0.0.1 is valid.",
    "Get geolocation information for IP address 8.8.8.8.",
    "List all environment variables on the current system.",
    "Get the temporary directory path of the current system.",
    "Get the username of the current system.",
    "Get the hostname of the current system.",
    "Get the operating system version information.",
    "Get the CPU model and core count of the current system.",
    "Get the total memory and available memory of the current system.",
    "Get the disk usage of all partitions on the current system.",
    "List all listening ports on the current system.",
    "Check if process with PID 1 is running.",
    "List all processes containing the keyword 'python'.",
    "Generate an 8-digit random numeric verification code.",
    "Generate a 24-character random alphanumeric string.",
    "Calculate the MD5 hash of the string 'Hippox Runtime'.",
    "Calculate the SHA256 hash of the string 'Hello World'.",
    "Base64 decode the string 'SGVsbG8gSGlwcG94'.",
    "Base64 encode the string 'Hippox AI'.",
    "Get the current ISO format timestamp.",
    "Get the current timestamp in milliseconds.",
    "Check if the current directory exists.",
    "List all hidden files in the current directory.",
    "Count the number of files in the current directory.",
    "Clear the system clipboard.",
    "Write 'Hippox AI Runtime' to the clipboard.",
    "Compare the difference between strings 'abc123' and 'abc456'.",
    "Remove duplicates from the list: [1, 2, 2, 3, 4, 4, 5].",
    "Extract the order number from the text 'Order number: ORD-12345678'.",
    "Validate whether the email 'test@example.com' format is correct.",
];

export const zhVideoEditorDefaultPrompts = [
    "请把第一个片段在 2.5 秒处裁剪开。",
    "请删除时间线上的第一个片段。",
    "请把第二个片段移动到 5 秒的位置。",
    "请把最后一个片段移动到 0 秒的位置。",
    "请给我看看当前项目的整体信息。",
    "请列出当前时间线上所有的轨道和片段。",
    "请给第一个片段应用复古滤镜，强度 0.8。",
    "请给第一个片段添加故障特效。",
    "请给第一个片段添加推拉镜头效果，时长 2 秒。",
    "请在第一个和第二个片段之间添加一个淡入淡出转场，时长 1 秒。",
    "请删除第一个片段上的滤镜。",
    "请删除第一个片段上的故障特效。",
    "请删除第一个片段上的运镜效果。",
    "请删除时间线上的第一个转场。",
    "请把 /home/user/videos/intro.mp4 导入到项目里。",
    "请下载 https://example.com/clip.mp4 并添加到时间线。",
    "请把这个贴纸加到视频里：https://example.com/cat.png",
    "请把素材 mat_abc123 添加到轨道，并在 2.5 秒处裁剪。",
    "请下载这个视频、添加到时间线并加复古滤镜：https://example.com/clip.mp4",
    "请把这个链接导入为素材：https://x.com/SpaceX/status/2099211149476569207",
    "请导出项目到 /home/user/videos，文件名 my_video。",
    "请导出当前项目。",
    "请把第一个覆盖物块移动到 3 秒的位置。",
    "请删除第一个覆盖物块。",
    "请把第二个覆盖物块在 1.5 秒处分割。",
    "请把第一段视频的起始时间改成 0 秒。",
    "请把最后一段视频的起始时间改成 10 秒。",
    "请给最后一段视频添加一个变焦运镜效果。",
    "请给最后一段视频应用黑白滤镜。",
    "请把第二个片段复制一份到时间线末尾。",
];

export const enVideoEditorDefaultPrompts = [
    "Trim the first clip at 2.5 seconds.",
    "Delete the first clip on the timeline.",
    "Move the second clip to 5 seconds.",
    "Move the last clip to 0 seconds.",
    "Show me the overall project information.",
    "List all tracks and clips on the current timeline.",
    "Apply a vintage filter to the first clip with intensity 0.8.",
    "Add a glitch effect to the first clip.",
    "Add a zoom-in camera motion to the first clip for 2 seconds.",
    "Add a cross dissolve transition between the first and second clip for 1 second.",
    "Remove the filter from the first clip.",
    "Remove the glitch VFX from the first clip.",
    "Remove the camera motion from the first clip.",
    "Remove the first transition on the timeline.",
    "Import /home/user/videos/intro.mp4 into the project.",
    "Download https://example.com/clip.mp4 and add it to the timeline.",
    "Add this sticker to my video: https://example.com/cat.png",
    "Add material mat_abc123 to the timeline and trim it at 2.5 seconds.",
    "Download this video, add it to the timeline, and apply a vintage filter: https://example.com/clip.mp4",
    "Import this link as material: https://x.com/SpaceX/status/2099211149476569207",
    "Export the project to /home/user/videos with file name my_video.",
    "Export the current project.",
    "Move the first overlay block to 3 seconds.",
    "Delete the first overlay block.",
    "Split the second overlay block at 1.5 seconds.",
    "Set the start time of the first video clip to 0 seconds.",
    "Set the start time of the last video clip to 10 seconds.",
    "Add a zoom camera motion to the last video clip.",
    "Apply a black and white filter to the last video clip.",
    "Duplicate the second clip to the end of the timeline.",
];

export const zhMapDefaultPrompts = [
    "请在地图上显示北京的位置。",
    "请在地图上标注上海、广州、深圳三个城市。",
    "请在纽约和洛杉矶之间画一条路线。",
    "请在我当前位置画一个 500 米半径的圆。",
    "请显示美国主要城市的人口热力图。",
    "请用条形图对比纽约、洛杉矶、芝加哥的人口。",
    "请显示黄石国家公园的边界。",
    "请在坐标 40.7128, -74.0060 处添加一个名为'总部'的标记。",
    "请把地图中心移动到东京，缩放级别 12。",
    "请显示中国所有省会城市的位置。",
    "请在地图上画出长江的走向。",
    "请显示全球主要港口的分布。",
    "请标注出欧洲所有国家的首都。",
    "请在地图上显示我所有的分公司位置。",
    "请在地图上画出 30 公里的通勤范围圈。",
    "请显示过去 24 小时发生地震的位置。",
    "请在地图上标注出所有机场的位置。",
    "请显示北京到上海的高铁线路。",
    "请在地图上画出这个区域的边界。",
    "请用不同颜色的标记区分不同类别的地点。",
    "请显示该城市的地铁线路图。",
    "请在地图上标注出所有加油站的位置。",
    "请显示这个地址周边 1 公里内的所有学校。",
    "请在地图上画出货运路线和途经点。",
    "请显示全球主要城市的时区分布。",
    "请标注出这个国家的所有邻国。",
    "请在地图上画出这片海域的边界。",
    "请显示该区域内的人口密度分布。",
    "请在地图上标注出所有世界遗产地。",
    "请画出从公司到最近的消防站的路线。",
];

export const enMapDefaultPrompts = [
    "Show the location of Beijing on the map.",
    "Mark the cities Shanghai, Guangzhou, and Shenzhen on the map.",
    "Draw a route between New York and Los Angeles.",
    "Draw a 500m radius circle around my current location.",
    "Show a population heatmap of major US cities.",
    "Compare the populations of NYC, LA, and Chicago with bar charts.",
    "Show the boundary of Yellowstone National Park.",
    "Add a marker named 'Headquarters' at coordinates 40.7128, -74.0060.",
    "Move the map center to Tokyo with zoom level 12.",
    "Show the locations of all provincial capitals in China.",
    "Draw the course of the Yangtze River on the map.",
    "Show the distribution of major global ports.",
    "Mark the capital cities of all European countries.",
    "Show the locations of all our branch offices on the map.",
    "Draw a 30km commuting range circle on the map.",
    "Show the locations of earthquakes in the past 24 hours.",
    "Mark all airports on the map.",
    "Show the high-speed rail line from Beijing to Shanghai.",
    "Draw the boundary of this region on the map.",
    "Use different colored markers to distinguish different categories of places.",
    "Show the subway map of this city.",
    "Mark all gas stations on the map.",
    "Show all schools within 1 km of this address.",
    "Draw the freight route and waypoints on the map.",
    "Show the time zone distribution of major global cities.",
    "Mark all neighboring countries of this nation.",
    "Draw the boundary of this sea area on the map.",
    "Show the population density distribution in this region.",
    "Mark all World Heritage Sites on the map.",
    "Draw the route from the office to the nearest fire station.",
];

export const zhCodeEditorDefaultPrompts = [
    "请把这个函数改成 async 函数。",
    "请给 login 函数添加 try-catch 错误处理。",
    "请创建一个 utils/format.ts 文件，包含 formatDate 函数。",
    "请移除已废弃的 oldApi 函数。",
    "请给这个组件添加 Props 类型定义。",
    "请把这段 for 循环改成 map 写法。",
    "请把所有 console.log 替换成统一的 logger 调用。",
    "请给 fetchData 函数添加参数校验。",
    "请把这个文件里的 var 全部改成 const 或 let。",
    "请把这个类拆分成多个小函数。",
    "请给这个接口请求添加超时处理。",
    "请把这段重复代码抽取成一个公共函数。",
    "请给这个函数添加 JSDoc 注释。",
    "请把回调写法改成 async/await。",
    "请修复这个文件里的 TypeScript 类型错误。",
    "请把这个函数拆成纯函数和副作用两部分。",
    "请给这个模块添加单元测试文件。",
    "请把硬编码的字符串提取成常量。",
    "请把这段 JS 代码迁移成 TypeScript。",
    "请给这个 API 请求增加重试机制。",
    "请优化这段代码的性能。",
    "请把所有的相对导入路径改成别名导入。",
    "请给这个组件添加 loading 和 error 状态。",
    "请把这段逻辑封装成自定义 Hook。",
    "请删除这个文件中未使用的导入。",
    "请给这个函数补全缺失的 return 语句。",
    "请把这段代码里的魔法数字改成具名常量。",
    "请给这个异步函数添加并发控制。",
    "请把这个文件里的 console.error 改成结构化日志。",
    "请给这个工具函数补充边界情况的处理。",
];

export const enCodeEditorDefaultPrompts = [
    "Convert this function to an async function.",
    "Add try-catch error handling to the login function.",
    "Create a utils/format.ts file with a formatDate function.",
    "Remove the deprecated oldApi function.",
    "Add Props type definitions to this component.",
    "Rewrite this for loop using map.",
    "Replace all console.log calls with a unified logger.",
    "Add parameter validation to the fetchData function.",
    "Change all var declarations in this file to const or let.",
    "Split this class into smaller functions.",
    "Add timeout handling to this API request.",
    "Extract this duplicated code into a shared helper function.",
    "Add JSDoc comments to this function.",
    "Convert the callback style to async/await.",
    "Fix the TypeScript type errors in this file.",
    "Split this function into a pure function and a side-effect part.",
    "Add a unit test file for this module.",
    "Extract hardcoded strings into constants.",
    "Migrate this JS code to TypeScript.",
    "Add a retry mechanism to this API request.",
    "Optimize the performance of this code.",
    "Convert all relative import paths to alias imports.",
    "Add loading and error states to this component.",
    "Wrap this logic into a custom Hook.",
    "Remove unused imports in this file.",
    "Add the missing return statement to this function.",
    "Replace magic numbers in this code with named constants.",
    "Add concurrency control to this async function.",
    "Replace console.error with structured logging in this file.",
    "Add edge case handling to this utility function.",
];

export const zhSandBox3DDefaultPrompts = [
    "请创建一个旋转的红色立方体。",
    "请创建一个带照明的蓝色金属球体。",
    "请创建一个包含地面、圆环和圆柱的场景。",
    "请创建一个由多个立方体组成的立方体矩阵。",
    "请创建一个绕中心旋转的圆环。",
    "请创建一个带金属质感的球体并加上橙色点光源。",
    "请创建一个漂浮在空中的圆锥体。",
    "请创建一个由 100 个小球组成的粒子球。",
    "请创建一个带动画的地球模型。",
    "请创建一个旋转的甜甜圈形状。",
    "请创建一个包含多个不同颜色立方体的场景。",
    "请创建一条从上到下流动的粒子流。",
    "请创建一个波浪起伏的地面平面。",
    "请创建一个旋转的金字塔。",
    "请创建一个简单的太阳系模型。",
    "请创建一个带纹理贴图的立方体。",
    "请创建一个弹跳的小球动画。",
    "请创建一个缓慢自转的陀螺。",
    "请创建一个由线条组成的 3D 网格。",
    "请创建一个漂浮的立方体阵列。",
    "请创建一个发光的球体。",
    "请创建一个带有阴影的立方体。",
    "请创建一个绕轨道运行的小球。",
    "请创建一个旋转的环形走廊。",
    "请创建一个透明的玻璃球体。",
    "请创建一个渐变色球体。",
    "请创建一个上下浮动的立方体。",
    "请创建一个由随机几何体组成的场景。",
    "请创建一个旋转的风车模型。",
    "请创建一个带环境光的简单室内场景。",
];

export const enSandBox3DDefaultPrompts = [
    "Create a rotating red cube.",
    "Create a blue metallic sphere with lighting.",
    "Create a scene with a ground plane, a torus, and a cylinder.",
    "Create a matrix of cubes.",
    "Create a torus rotating around its center.",
    "Create a metallic sphere with an orange point light.",
    "Create a cone floating in the air.",
    "Create a particle sphere made of 100 small balls.",
    "Create an animated Earth model.",
    "Create a rotating donut shape.",
    "Create a scene with several cubes in different colors.",
    "Create a particle stream flowing from top to bottom.",
    "Create a wavy undulating ground plane.",
    "Create a rotating pyramid.",
    "Create a simple solar system model.",
    "Create a cube with a texture map.",
    "Create a bouncing ball animation.",
    "Create a slowly spinning top.",
    "Create a 3D wireframe grid.",
    "Create a floating array of cubes.",
    "Create a glowing sphere.",
    "Create a cube with shadows.",
    "Create a small ball orbiting around a center.",
    "Create a rotating ring corridor.",
    "Create a transparent glass sphere.",
    "Create a gradient colored sphere.",
    "Create a cube floating up and down.",
    "Create a scene with random geometric shapes.",
    "Create a rotating windmill model.",
    "Create a simple indoor scene with ambient light.",
];

export const zhFinanceDefaultPrompts = [
    "请分析 BTC/USDT 的日线走势。",
    "请加载 ETH/USDT 的 1 小时图表。",
    "请给 BTC/USDT 图表添加 MA20 均线。",
    "请给 ETH/USDT 添加 RSI 和 MACD 指标。",
    "请在 BTC/USDT 图表上标记 50000 的买入点。",
    "请分析 AAPL 的近期走势并给出建议。",
    "请加载特斯拉 TSLA 的日线图表。",
    "请分析 002384 东山精密并给出完整分析。",
    "请分析 600519 贵州茅台的资金流向。",
    "请给 BTC/USDT 添加布林带指标。",
    "请分析黄金 XAU/USD 的支撑和阻力位。",
    "请分析美元指数 DXY 的近期趋势。",
    "请加载纳斯达克指数 NDX 的周线图表。",
    "请给 BTC/USDT 图表添加自定义成交量指标。",
    "请在 ETH/USDT 图表上标记超卖信号。",
    "请分析英伟达 NVDA 的财报数据。",
    "请分析 000001 上证指数的市场情绪。",
    "请给 AAPL 添加 KDJ 指标并分析买卖信号。",
    "请分析 BTC/USDT 当前的多空力量对比。",
    "请加载亚马逊 AMZN 的日线图表并标注关键价位。",
    "请分析 300750 宁德时代的行业地位和估值。",
    "请给 ETH/USDT 添加 ATR 指标用于风险控制。",
    "请分析白银 XAG/USD 的技术面。",
    "请分析标普 500 指数 SPX 的估值水平。",
    "请给 BTC/USDT 图表添加 VWAP 指标。",
    "请分析微软 MSFT 的市盈率和目标价。",
    "请分析 002594 比亚迪的财务数据。",
    "请对比 BTC 和 ETH 的近期表现。",
    "请给 BTC/USDT 图表标记头肩顶形态。",
    "请分析人民币兑美元 USD/CNY 的近期走势。",
];

export const enFinanceDefaultPrompts = [
    "Analyze the daily chart of BTC/USDT.",
    "Load the 1-hour chart of ETH/USDT.",
    "Add a MA20 moving average to the BTC/USDT chart.",
    "Add RSI and MACD indicators to ETH/USDT.",
    "Mark a buy point at 50000 on the BTC/USDT chart.",
    "Analyze the recent trend of AAPL and give suggestions.",
    "Load the daily chart of Tesla TSLA.",
    "Analyze 002384 Dongshan Precision and give a full analysis.",
    "Analyze the fund flow of 600519 Kweichow Moutai.",
    "Add Bollinger Bands to the BTC/USDT chart.",
    "Analyze the support and resistance of Gold XAU/USD.",
    "Analyze the recent trend of the US Dollar Index DXY.",
    "Load the weekly chart of the Nasdaq Index NDX.",
    "Add a custom volume indicator to the BTC/USDT chart.",
    "Mark the oversold signal on the ETH/USDT chart.",
    "Analyze the financials of NVIDIA NVDA.",
    "Analyze the market sentiment of the Shanghai Composite Index 000001.",
    "Add KDJ to AAPL and analyze buy/sell signals.",
    "Analyze the current bull/bear balance on BTC/USDT.",
    "Load the daily chart of Amazon AMZN and mark key levels.",
    "Analyze the industry position and valuation of 300750 CATL.",
    "Add ATR to ETH/USDT for risk control.",
    "Analyze the technicals of Silver XAG/USD.",
    "Analyze the valuation level of the S&P 500 Index SPX.",
    "Add VWAP to the BTC/USDT chart.",
    "Analyze the PE ratio and target price of Microsoft MSFT.",
    "Analyze the financial data of 002594 BYD.",
    "Compare the recent performance of BTC and ETH.",
    "Mark the head-and-shoulders pattern on the BTC/USDT chart.",
    "Analyze the recent trend of USD/CNY.",
];