/**
 * Task information - represents a complete task execution unit
 * 
 * A TaskInfo represents a single task request initiated by the user, containing 
 * all information from task creation to completion.
 * Each task can contain multiple steps (TaskStepInfo) executed in sequence.
 * 
 * Lifecycle: Created → Pending → Running → Completed/Failed/Cancelled
 * 
 * Relationships:
 * - One TaskInfo contains many TaskStepInfo (one-to-many relationship)
 * - One TaskInfo belongs to one Session (via session_id)
 * - TaskInfo is uniquely identified by task_id
 * 
 * Data Flow:
 * 1. User sends message → TaskInfo created (status: Pending)
 * 2. Backend starts execution → status updated to Running, steps begin to be added
 * 3. Each step executes → TaskStepInfo added/updated
 * 4. Task completes → status updated to Completed, final_output saved
 * 5. Task fails → status updated to Failed, error saved
 */
export interface TaskInfo {
    /** Unique task identifier, generated by the backend */
    task_id: string;
    /** ID of the session this task belongs to, used for task grouping and retrieval */
    session_id: string;
    /** Original user input/prompt that triggered this task */
    user_input: string;
    /** Current execution status of the task */
    status: TaskStatusEnum;
    /** List of execution steps contained within this task (ordered by step_index) */
    steps: TaskStepInfo[];
    /** Final output result after task completion */
    final_output?: string;
    /** Raw output from the backend before processing */
    rawOutput?: string;
    /** Error message if the task failed */
    error?: string;
    /** Total execution duration in milliseconds */
    total_duration_ms?: number;
    /** Total number of steps executed */
    total_steps?: number;
    /** Creation timestamp (ISO format) */
    created_at: string;
    /** Last update timestamp (ISO format) */
    updated_at: string;
    /** Timestamp when execution started (ISO format) */
    started_at?: string;
    /** Timestamp when execution completed (ISO format) */
    completed_at?: string;
    /** Individual step execution duration in milliseconds */
    duration_ms?: number;
    /** Execution progress percentage (0-100) */
    progress?: number;
    /** Checkpoint data for resuming paused tasks */
    resume_data?: string | null;
    /** Files uploaded as part of this task */
    files?: UploadFile[];
    workflow_mode?: string;
    /**
    * Whether the LLM function commands from this task have been executed.
    * Used to prevent duplicate execution of the same task.
    */
    executed?: boolean;
}
/**
* Task step information - represents a single execution step within a task
* 
* A TaskStepInfo represents one atomic operation/action executed as part of a larger task.
* Steps are executed sequentially and each step's output serves as context for subsequent steps.
* 
* Relationships:
* - Many TaskStepInfo belong to one TaskInfo (many-to-one relationship)
* - Steps are ordered by step_index
* - Each step belongs to the parent task via the containing TaskInfo
* 
* Execution Flow:
* 1. Step starts → status: RUNNING, started_at set, log added
* 2. Step progresses → progress updates (0-100), progress_message updates, log added
* 3. Step completes → status: SUCCESS, output set, completed_at set, log added
* 4. Step fails → status: FAILURE, error set, completed_at set, log added
*/
export interface TaskStepInfo {
    /** Step order/index within the parent task (0-based) */
    step_index: number;
    /** Name of the skill/action being executed */
    step_name: string;
    /** Current execution status of this step */
    status: StepStatusEnum;
    /** Error message if this step failed */
    error?: string;
    /** Duration of this step execution in milliseconds */
    duration_ms?: number;
    /** JSON string of input parameters passed to this step */
    input?: string;
    /** Output/result from this step execution, JSON string of output to this step */
    output?: string;
    /** Real-time execution progress of this step (0-100), from skill_callback_progress */
    progress?: number;
    /** Human-readable progress message, from skill_callback_progress */
    progress_message?: string;
    /** Start timestamp of this step (ISO format), from skill_callback_start */
    started_at?: string;
    /** Completion timestamp of this step (ISO format), from skill_callback_complete or skill_callback_error */
    completed_at?: string;
    /** 
     * Execution logs for this step, each string represents one log line
     * Collected from all skill events (start, progress, complete, error)
     */
    logs?: string[];
}
export enum TaskStatusEnum {
    Pending = "pending",
    Running = "running",
    Paused = "paused",
    Completed = "completed",
    Cancelled = "cancelled",
    Failed = "failed",
    Timeout = "timeout",
}
export enum StepStatusEnum {
    Waiting = "WAITING",
    Running = "RUNNING",
    Success = "SUCCESS",
    Failure = "FAILURE",
    Skipped = "skipped",
    Timeout = "TIMEOUT",
    Paused = "paused",
    Cancelled = "cancelled",
}
export interface UploadFile {
    id: string;
    file: File;
    name: string;
    size: number;
    type: string;
    content?: string;
    preview?: string;
    status: "uploading" | "success" | "error";
    progress?: number;
    path?: string;
}
export enum SessionDomain {
    General = "general",
    Chart = "chart",
    Map = "map",
    CodeEditor = "codeeditor",
    Video = "video",
    SandBox3D = "sandbox3d",
}
